title:              apase
description:        "- apase (lat. apasus), noun, feminine, a|pa|se, /ʌpʌzɘ/, adjective: apasing"
author:             Helene Herwig
baseurl:            "/"
url:                "https://heleneherwig.github.io"

# Social Profiles
soundcloud_username: hell_jaa
instagram_username:  therealapase
twitter_username:    hehe_29

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
